module.exports = {
  defaultSidebar: [
    {
      type: 'link',
      label: 'What is Gitea?',
      href: '/next/'
    },
    {
      type: 'category',
      label: 'Installation',
      items: [
          {
          type: 'autogenerated',
          dirName: 'installation',
          }
      ]
    },
    {
      type: 'category',
      label: 'Administration',
      items: [
          {
          type: 'autogenerated',
          dirName: 'administration',
          }
      ]
    },
    {
      type: 'category',
      label: 'Usage',
      items: [
          {
            type: 'category',
            label: 'Actions',
            items: [
                {
                type: 'autogenerated',
                dirName: 'actions',
                }
            ]
          },
          {
            type: 'category',
            label: 'Packages',
            items: [
                {
                type: 'autogenerated',
                dirName: 'usage/packages',
                }
            ]
          },
          {
            type: 'autogenerated',
            dirName: 'usage',
          }
      ]
    },
    {
      type: 'category',
      label: 'Development',
      items: [
          {
          type: 'autogenerated',
          dirName: 'development',
          }
      ]
    },
    {
      type: 'category',
      label: 'Contributing',
      items: [
          {
          type: 'autogenerated',
          dirName: 'contributing',
          }
      ]
    },
    {
      type: 'category',
      label: 'Help',
      items: [
          {
          type: 'autogenerated',
          dirName: 'help',
          }
      ]
    },
  ],
  siderBarCN: [
    {
      type: 'link',
      label: 'Gitea是什么？',
      href: 'zh-cn/next/'
    },
    {
      type: 'category',
      label: '安装',
      items: [
          {
          type: 'autogenerated',
          dirName: 'zh-cn/installation',
          }
      ]
    },
    {
      type: 'category',
      label: '管理',
      items: [
          {
          type: 'autogenerated',
          dirName: 'zh-cn/administration',
          }
      ]
    },
    {
      type: 'category',
      label: '使用',
      items: [
          {
            type: 'category',
            label: '软件包管理',
            items: [
                {
                type: 'autogenerated',
                dirName: 'zh-cn/packages',
                }
            ]
          },
          {
            type: 'autogenerated',
            dirName: 'zh-cn/usage',
          }
      ]
    },
    {
      type: 'category',
      label: '开发',
      items: [
          {
          type: 'autogenerated',
          dirName: 'zh-cn/development',
          }
      ]
    },
    {
      type: 'category',
      label: '贡献',
      items: [
          {
          type: 'autogenerated',
          dirName: 'zh-cn/contributing',
          }
      ]
    },
    {
      type: 'category',
      label: '帮助',
      items: [
          {
          type: 'autogenerated',
          dirName: 'zh-cn/help',
          }
      ]
    },
  ],
};